import React from 'react'
import Head from 'next/head'

import Logo from "../components/svg/logo-distritodev.svg"

function Header() {
    return (
        <>
            <Head>
                <title>DistritoDev</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header className=" bg-primary-color">
                <nav className="custom-container flex justify-between py-8 relative">
                    <Logo />
                    <input id="menu" className='peer/menu absolute hidden w-0' type="checkbox" name="menu"/>
                    <label htmlFor="menu" className='md:hidden cursor-pointer text-3xl'>☰</label>

                    <div className="max-h-0 peer-checked/menu:max-h-96 transition-all duration-300 overflow-hidden absolute right-0 w-full text-left mt-16 bg-secondary-color md:w-auto md:relative md:mt-0 md:max-h-96 md:bg-inherit md:text-right">
                        <ul className="pt-8 md:pt-0 md:flex">
                            <li className="menu-item"><a href="#" className="">Inicio</a></li>
                            <li className="menu-item"><a href="#" className="">Servicios</a></li>
                            <li className="menu-item"><a href="#" className="">Quienes somos</a></li>
                            <li className="menu-item"><a href="#" className="">Portfolio</a></li>
                            <li className="menu-item"><a href="#" className="">Cotiza</a></li>
                        </ul>
                    </div>
                </nav>
            </header>
        </>
    )
}

export default Header